server:
  port: 9001
  tomcat:
    # ??????? TCP ??? ???? ??? HTTP ??? ???? ??? ??? ???? ??
    connection-timeout: 2s
    # ??? HTTP ??? ???? ?? ??? ???? ??
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

polar:
  greeting: Welcome to the local project


spring:
  application:
    name: catalog-service