server:
  port: 9001
  tomcat:
    # 클라이언트에서 TCP 연결을 수락하고 실제로 HTTP 요청을 받기까지 톰캣이 최대한 기다리는 시간
    connection-timeout: 2s
    # 새로운 HTTP 요청을 기다리는 동안 연결을 유지하는 시간
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

polar:
  greeting: Welcome to the local project