server:
  port: 8761 # ??? ??? ???? ??

# Spring Cloud?? ??? MSA ID? ?? ????? ? ??? ????.
spring:
  application:
    name: discovery

eureka:
  client:
    register-with-eureka: false # ?? ??? ?????? ???? ??
    fetch-registry: false # ????? ???? ????(???) ?? ??
  server:
    wait-time-in-ms-when-sync-empty: 5 # ??? ?? ?? ? ??? ?? ??

---
spring:
  config:
    activate:
      on-profile: eureka2

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://DOWONui-MacBookPro.local:8763/eureka/
  instance:
    hostname: localhost

---
spring:
  config:
    activate:
      on-profile: eureka3

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: DOWONui-MacBookPro.local